// Bundles shopify-theme/ into convex/lib/themeFiles.generated.ts, so the
// Convex backend can serve the storefront theme as a zip (convex/storeThemeHttp.ts).
// Run after changing anything in shopify-theme/:  node scripts/build-theme.mjs
// convex/storeTheme.test.ts fails while the generated file is out of date.

import { readdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { join, relative, sep } from "node:path";
import { fileURLToPath } from "node:url";

const repo = join(fileURLToPath(import.meta.url), "..", "..");
const themeDir = join(repo, "shopify-theme");

export function readTheme(dir = themeDir) {
  const files = {};
  const walk = (d) => {
    for (const name of readdirSync(d).sort()) {
      const p = join(d, name);
      if (statSync(p).isDirectory()) walk(p);
      else files[relative(dir, p).split(sep).join("/")] = readFileSync(p, "utf8").replace(/\r\n/g, "\n");
    }
  };
  walk(dir);
  return files;
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  const files = readTheme();
  const out =
    "// Generated by scripts/build-theme.mjs from shopify-theme/. Don't edit by hand.\n" +
    "/* eslint-disable */\n" +
    `export const THEME_FILES: Record<string, string> = ${JSON.stringify(files, null, 1)};\n`;
  writeFileSync(join(repo, "convex", "lib", "themeFiles.generated.ts"), out);
  console.log(`${Object.keys(files).length} theme files bundled`);
}
